server:
  port: 8080
spring:
  application:
    name: spring-boot-blueprint-base
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5455/blueprint
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true
  jwt:
    # After working with Auth, then create the (.evn) file and add a secret key {JWT_SECRET=secret}
    secret: {JWT_SECRET}
    accessTokenExpiration: 900 # 15 minutes
    refreshTokenExpiration: 86400 # 1 day